name: E2E Build Image
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - "master"
jobs:
  upload-test-image:
    runs-on: ubuntu-latest
    steps:
      - name: Build test image
        run: |
          docker build -t test_image:${{ github.run_id }} -<<EOF
            FROM busybox
            RUN touch abc.txt
          EOF

      - name: Upload image
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: "test_image:${{ github.run_id }}"

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: run-e2e-from-workflow
          client-payload: '{"image": "test_image:${{ github.run_id }}", "workflow": "${{ github.workflow }}"}'
